
parameters:
  StageName: ''
  DependsOn: ''
  EnvironmentResource: ''
  vmImageName: ''
  imagePullSecret: ''
  dockerRegistryServiceConnection: ''
  containerRegistry: ''
  imageRepository: ''
  tag: ''

stages:
- stage: ${{ parameters.StageName }} 
  dependsOn: ${{ parameters.DependsOn }} 
  displayName: ${{ parameters.StageName }} stage
  jobs:
  - deployment: deploy
    environment: ${{ parameters.EnvironmentResource }}  
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo abc
