
parameters:
  StageName: ''
  DependsOn: ''
  EnvironmentResource: ''
  vmImageName: ''
  imagePullSecret: ''
  dockerRegistryServiceConnection: ''
  containerRegistry: ''
  imageRepository: ''
  tag: ''

stages:
- stage: ${{ parameters.StageName }}  
  jobs:
  - job: ${{ parameters.name }}_Windows
    steps:
    - script: echo abc
