apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: shashbanexpressaks 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shashbanexpressaks 
    spec:
      containers:
        - name: shashbanexpressaks 
          image: atulmakshelm.azurecr.io/shashbanexpressaks 
          ports:
          - containerPort: 3000